name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - name: install
        run:  npm ci

      - name: build standalone
        run:  npm run build:standalone

      - name: build module
        run:  npm run build:module

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: lib umd README.MD
